/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GastosRouteImport } from './routes/gastos'
import { Route as RendicionesRouteImport } from './routes/rendiciones'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GastosRoute = GastosRouteImport.update({
  id: '/gastos',
  path: '/gastos',
  getParentRoute: () => rootRouteImport,
} as any)
const RendicionesRoute = RendicionesRouteImport.update({
  id: '/rendiciones',
  path: '/rendiciones',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gastos': typeof GastosRoute
  '/rendiciones': typeof RendicionesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gastos': typeof GastosRoute
  '/rendiciones': typeof RendicionesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gastos': typeof GastosRoute
  '/rendiciones': typeof RendicionesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/gastos' | '/rendiciones'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/gastos' | '/rendiciones'
  id: '__root__' | '/' | '/gastos' | '/rendiciones'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GastosRoute: typeof GastosRoute
  RendicionesRoute: typeof RendicionesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gastos': {
      id: '/gastos'
      path: '/gastos'
      fullPath: '/gastos'
      preLoaderRoute: typeof GastosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rendiciones': {
      id: '/rendiciones'
      path: '/rendiciones'
      fullPath: '/rendiciones'
      preLoaderRoute: typeof RendicionesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GastosRoute: GastosRoute,
  RendicionesRoute: RendicionesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
